import { currentFounderTier } from '@/lib/priceLadder'
import type { Metadata } from 'next'
export const metadata: Metadata = { title:'Founder Pricing • PropertyBuyerConnection', description:'Lock a low founder rate, add unlimited listings, and get buyer traffic with alerts and lead capture. Canada & US.', openGraph:{ title:'Founder Pricing • PropertyBuyerConnection', description:'Lock a low founder rate, add unlimited listings, and get buyer traffic with alerts and lead capture.', type:'website' } }
function formatUSD(n:number){ return `$${n.toLocaleString()}/mo` }
function ladderDates(launchISO:string){ const launch=new Date(launchISO+'T00:00:00Z'); const tier1End=new Date(launch); tier1End.setUTCMonth(launch.getUTCMonth()+2); const tier2End=new Date(launch); tier2End.setUTCMonth(launch.getUTCMonth()+4); const tier3End=new Date(launch); tier3End.setUTCMonth(launch.getUTCMonth()+6); return {tier1End,tier2End,tier3End} }
const checklist=['Unlimited listing entries (link to your own full listing pages)','Map search with draw-radius/shape','Saved searches + buyer alerts (email & web push)','Lead form with hCaptcha + rate limiting','Simple agent dashboard & CSV import','Admin moderation for quality']
const faqs=[{q:'What happens if I cancel?',a:'If you cancel and later return, you\'ll re-subscribe at $200/mo instead of your founder rate.'},{q:'Is there a free trial?',a:'No trial. The founder waves are the discount — lock them in while they last.'},{q:'Where is this available?',a:'Canada and the United States.'},{q:'Do I need photos?',a:'No. We use your existing listing URL as the click-through. You control your photos on your own site/MLS page.'},{q:'How do buyer alerts work?',a:'Buyers save an area or shape; when new listings match, we send alerts instantly or in a daily digest.'}]
export default function FounderPage(){ const launchISO=process.env.LAUNCH_DATE || new Date().toISOString().slice(0,10); const {tier1End,tier2End,tier3End}=ladderDates(launchISO); const tier=currentFounderTier(); const price=tier==='50'?50:tier==='100'?100:tier==='150'?150:200; const cards=[{label:'$50/mo',sub:'Founder Wave 1',until:tier1End,active:tier==='50'},{label:'$100/mo',sub:'Founder Wave 2',until:tier2End,active:tier==='100'},{label:'$150/mo',sub:'Founder Wave 3',until:tier3End,active:tier==='150'},{label:'$200/mo',sub:'Standard',until:null as Date | null,active:tier==='200'}]; return(<div className='grid gap-8'>
  <div className='card'><div className='flex items-start justify-between gap-4'><div><img src='/pbc-logo.svg' alt='PropertyBuyerConnection' className='h-8 mb-3'/><h1 className='text-3xl font-semibold'>Founder pricing — keep it for as long as you stay active</h1><p className='text-gray-600 mt-2'>Add your listings once, send buyers to your own URLs, and capture leads with alerts. Canada & US.</p></div><a className='btn-primary h-10' href='/api/stripe/checkout'>Subscribe at {formatUSD(price)}</a></div><div className='mt-6 grid sm:grid-cols-2 lg:grid-cols-4 gap-3'>{cards.map((c,i)=>(<div key={i} className={`rounded-2xl border p-4 ${c.active?'border-black':'border-gray-200'}`}><div className='text-2xl font-semibold'>{c.label}</div><div className='text-sm text-gray-600'>{c.sub}</div><div className='text-xs mt-1'>{c.until?<>Available until <strong>{c.until.toLocaleDateString()}</strong></>:'Ongoing'}</div>{c.active&&<div className='mt-2 inline-block bg-black text-white text-xs px-2 py-1 rounded'>Current</div>}</div>))}</div><p className='text-xs text-gray-600 mt-3'>If you cancel and return later, re-subscribe pricing is <strong>$200/mo</strong> — founder rates don’t carry over.</p></div>
  <div className='grid lg:grid-cols-3 gap-6'><div className='card lg:col-span-2'><h2 className='text-lg font-semibold mb-2'>Everything you need to get buyers to your listings</h2><ul className='list-disc pl-5 text-sm text-gray-800 space-y-1'>{checklist.map((c,i)=>(<li key={i}>{c}</li>))}</ul><div className='grid sm:grid-cols-3 gap-3 mt-6'><div className='rounded-xl border p-3'><div className='font-medium'>Bring your own listing URL</div><p className='text-sm text-gray-600'>No media uploads. Link straight to your MLS/website pages for full control.</p></div><div className='rounded-xl border p-3'><div className='font-medium'>Buyer alerts that feel helpful</div><p className='text-sm text-gray-600'>Instant when there’s a match, daily digest otherwise. No spam blasts.</p></div><div className='rounded-xl border p-3'><div className='font-medium'>Simple, predictable pricing</div><p className='text-sm text-gray-600'>One monthly plan during the founder waves. Lock it in while it’s available.</p></div></div></div><div className='card'><h2 className='text-lg font-semibold mb-2'>Ready to lock your rate?</h2><p className='text-sm text-gray-600'>Secure checkout via Stripe. Cancel anytime.</p><a className='btn-primary mt-3 inline-flex' href='/api/stripe/checkout'>Subscribe at {formatUSD(price)}</a><a className='btn mt-3 inline-flex' href='/api/stripe/portal'>Manage billing</a><div className='text-xs text-gray-600 mt-3'>By subscribing you agree to our fair-use and moderation policies to keep listing quality high.</div></div></div>
  <div className='card'><h2 className='text-lg font-semibold mb-3'>Founder FAQs</h2><div className='grid gap-3'>{faqs.map((f,i)=>(<details key={i} className='rounded-xl border p-3'><summary className='font-medium cursor-pointer'>{f.q}</summary><p className='text-sm text-gray-700 mt-2'>{f.a}</p></details>))}</div><script type='application/ld+json' dangerouslySetInnerHTML={{__html: JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity": faqs.map(f=>({"@type":"Question","name":f.q,"acceptedAnswer":{"@type":"Answer","text":f.a}}))})}}/></div>
  <div className='text-xs text-gray-600 text-center'>© {new Date().getFullYear()} PropertyBuyerConnection • Secure payments by Stripe</div>
</div>)}
